package dpfm_api_output_formatter

func ConvertToGooglePlacesLocationsRequestsFromResponse(
	googlePlacesLocationsRequestsResponseBody GooglePlacesLocationsResponseBody,
) GooglePlacesLocationsResponse {
	var googlePlacesLocationsRequestsResponse GooglePlacesLocationsResponse

	googlePlacesLocationsRequestsResponse.PlaceID = googlePlacesLocationsRequestsResponseBody.PlaceID
	googlePlacesLocationsRequestsResponse.Description = googlePlacesLocationsRequestsResponseBody.Description
	googlePlacesLocationsRequestsResponse.IconURI = googlePlacesLocationsRequestsResponseBody.IconURI
	googlePlacesLocationsRequestsResponse.IconBackgroundColorInHex = googlePlacesLocationsRequestsResponseBody.IconBackgroundColorInHex
	googlePlacesLocationsRequestsResponse.IconMaskBaseURI = googlePlacesLocationsRequestsResponseBody.IconMaskBaseURI
	googlePlacesLocationsRequestsResponse.Rating = googlePlacesLocationsRequestsResponseBody.Rating
	googlePlacesLocationsRequestsResponse.UserRatingsTotal = googlePlacesLocationsRequestsResponseBody.UserRatingsTotal
	googlePlacesLocationsRequestsResponse.Vicinity = googlePlacesLocationsRequestsResponseBody.Vicinity
	googlePlacesLocationsRequestsResponse.BusinessStatus = googlePlacesLocationsRequestsResponseBody.BusinessStatus
	googlePlacesLocationsRequestsResponse.Photos = googlePlacesLocationsRequestsResponseBody.Photos
	googlePlacesLocationsRequestsResponse.Geometry = googlePlacesLocationsRequestsResponseBody.Geometry
	googlePlacesLocationsRequestsResponse.Types = googlePlacesLocationsRequestsResponseBody.Types
	googlePlacesLocationsRequestsResponse.OpeningHours = googlePlacesLocationsRequestsResponseBody.OpeningHours

	return googlePlacesLocationsRequestsResponse
}
